const { test, expect } = require('@playwright/test');

test('owner workspace and client portal work on desktop and mobile',async({browser,page},testInfo)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:/Great client work/})).toBeVisible();
 await page.screenshot({path:testInfo.outputPath('landing.png'),fullPage:true});
 await page.getByRole('button',{name:'Create workspace',exact:true}).click();
 await page.getByLabel('Your name').fill('Sanjay');
 await page.getByLabel('Email address',{exact:true}).fill('browser-owner@example.test');
 await page.getByLabel('Workspace / agency name').fill('Medfluence');
 await page.getByLabel('Choose a password').fill('BrowserPassword123!');
 await page.getByRole('button',{name:'Create workspace',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Hello, Sanjay.'})).toBeVisible();
 await page.getByRole('button',{name:'Clients',exact:true}).click();
 await page.getByRole('button',{name:'Add client',exact:true}).click();
 await page.getByLabel('Contact name').fill('Dr Example');
 await page.getByLabel('Company / clinic').fill('Example Clinic');
 await page.getByLabel('Email address').fill('browser-client@example.test');
 await page.getByRole('button',{name:'Save client',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Example Clinic'})).toBeVisible();
 await page.getByRole('button',{name:'Projects',exact:true}).click();
 await page.getByRole('button',{name:'Add project',exact:true}).click();
 await page.getByLabel('Project name').fill('October content');
 await page.getByLabel('Client',{exact:true}).selectOption({label:'Example Clinic'});
 await page.getByLabel('Description').fill('15 reels and a clear monthly content plan.');
 await page.getByLabel('Project budget').fill('35000');
 await page.getByLabel('Status',{exact:true}).selectOption('In review');
 await page.getByRole('button',{name:'Save project',exact:true}).click();
 await expect(page.getByRole('button',{name:'October content',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Tasks',exact:true}).click();
 await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByLabel('Task title').fill('Edit the first reel');
 await page.getByLabel('Project',{exact:true}).selectOption({label:'October content'});
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Edit the first reel'})).toBeVisible();
 await page.getByRole('button',{name:'Invoices',exact:true}).click();
 await page.getByRole('button',{name:'Create invoice',exact:true}).click();
 await page.getByLabel('Client',{exact:true}).selectOption({label:'Example Clinic'});
 await page.getByLabel('Item 1 description').fill('Content production');
 await page.getByLabel('Item 1 unit price').fill('35000');
 await page.getByLabel('Tax rate (%)').fill('18');
 await page.getByRole('button',{name:'Create draft invoice'}).click();
 await page.getByRole('button',{name:'Issue',exact:true}).click();
 await expect(page.getByText('Sent',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Record payment',exact:true}).click();
 await page.getByLabel('Amount received').fill('20000');
 await page.getByLabel('Payment reference / method').fill('UPI test');
 await page.getByRole('dialog').getByRole('button',{name:'Record payment',exact:true}).click();
 await expect(page.getByText('Part paid',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.screenshot({path:testInfo.outputPath('dashboard.png'),fullPage:true});
 await page.getByRole('button',{name:'Clients',exact:true}).click();
 await page.getByRole('button',{name:'Invite to portal'}).click();
 await page.getByRole('button',{name:'Create invitation link'}).click();
 const invite=await page.getByLabel('Private invitation link').inputValue();
 const clientContext=await browser.newContext();const clientPage=await clientContext.newPage();
 await clientPage.goto(invite);
 await clientPage.getByLabel('Your name').fill('Dr Example');
 await clientPage.getByLabel('Choose a password').fill('ClientBrowserPassword123!');
 await clientPage.getByRole('button',{name:'Join workspace'}).click();
 await expect(clientPage.getByRole('heading',{name:'Hello, Dr.'})).toBeVisible();
 await clientPage.getByRole('button',{name:'Projects',exact:true}).click();
 await clientPage.getByRole('button',{name:'Open project'}).click();
 await clientPage.getByRole('button',{name:'Approve delivery'}).click();
 await expect(clientPage.getByRole('button',{name:'Leave a review'})).toBeVisible();
 await clientContext.close();
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Open navigation'}).click();
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Hello, Sanjay.'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.locator('.sidebar')).not.toBeVisible();
 await page.screenshot({path:testInfo.outputPath('mobile.png'),fullPage:true});
 expect(errors).toEqual([]);
});
